dist: trusty
sudo: required
language: java
jdk:
- openjdk8
python:
- '2.7'
env:
  global:
  - GH_REF=github.com/ldbc/ldbc_snb_datagen.git
  - secure: CkvlhK6IfI4meJVYmMzR6aOVciQgps0OCRk+CD6HBLsM+xKphjN0L/Tq4z/yeNT4WjV5pLqNvfAUX4RdfdDwjSWbdmjpuJPNu6AilYBRCP6LVM+v76phsNFaFK2cU+BNMyFmunv8JK70hM5VV+A+h2BbkIeVCzUkMIVOzh+SRqogx7CreGopCrvvJm4ai65+2JIuWanduIBWmI8YiSkq6/41Nb9Nyi3z7szNHoADjF/fS1rbGjwXehRWKrbKjSQvP3WNEHgvEHDqWzRoatdQuBQm5SDXjJYYCpxqpXDQJnClOpItkNCrFUm0tU9ZtZUhu91IjNCBZO1DzrdwhsBjQC79gk8opCDKq9FyBJvtQiOSBgkFvifY+Fz9KGJ4V4k3ixZst1WflsRYP9N9byRhDRPOgohFjCNAhGeqc8HHJe1/0SY3QTCiQY7PvosxXE7jrfSgbsfv0iVSVgTiATcQH5f+27/UjQpeCDsssoLU18OtGfcHSYn2UVUo/GKgOmnvTnPhfGcRKG1rMj9ZgwQHAF1WO1ZNlM+SnD2dCJk3Z0t4SUMlDuurn7LuHh+3Xl5eLxYxBzogLN9jQK3PwPuMcDBSBCBhyHmEHXaqX+AUiKEhsCMKqSF4VDjwtRRP2nkbFF/I1jxKo635R/dd1dQJQETEJI6Vicf1P/K0jtN1iyQ=
  - secure: UG0OiJIFnm9mlQvV62cRwZzRFclw1Tu1QTFTUvEVcyskFV7fvIZjVZ1ozvIs8arfVulHXnijWYOr4X76HqB4bEMCpuk47nTk6zA+8omC+IVML1C8Mq0yT7L0k9iCShPOylAtvTqUMtrgewYXINqsQQxunqwWsIoeIdFh3wC+Km+0k2/NlxGlsCj4ajP1reGcYxj9b51mjskAC4EueJn0mgd7uFS3C92hJEaFovKUykpnVx9Vx54ssm2QkTtijdGiEUtps8b93dQQ0wQ/KShTQ6HiHr60Z0pt5PGThVT7EeO9RSHEJjIGhK+UKEf6ab0yxWjQxoIGjXEE19orVA+hLiHq9nnAQK293Y6+J6Qc6s+HI2PTrymI3kQGi3KcTN/K9ukW2wfulxX4R/nTFAtWJK4MMmMBahC+t2dSeKDKbq0yzFfFaSgFPLfDcfe/aQ/YBWFDhbvAqWmguMTcwreNeZMvMNLDdRCY3uXMOjqVEhxbJItbyhXCYTnPgdDDKcaJO2GaOadSzZdomwFhqpKjOca9ynVes1NX1Q+jv9E1862l9D8gkWGiMekMW2IhaVZTQvp1V77TCJ+az4jJVmTPdMAjiQvyisKFzC39xYUix11fYuZOTKQjPB1r4CUwVTTS649n6VwGukE0OdnzEFqbMHql6iV4ODQlHEO+syNbAOM=
script:
- mvn test | grep "^\\["
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then ./deploy.sh;
  fi
notifications:
  slack: ldbcouncil:OrBanrJ7l0EHQbj8T5YdJYhd
  email: false
  on_success: change
  on_failure: always
