language: java
jdk:
- openjdk8
python:
- '2.7'
install: true
script:
- mvn test | grep "^\\[" | tee mvn.log
# test if the output of the mvn command contained an "[INFO] BUILD SUCCESS" entry
- grep 'BUILD SUCCESS' mvn.log
# generate SF1 data set
- wget -q http://archive.apache.org/dist/hadoop/core/hadoop-2.6.0/hadoop-2.6.0.tar.gz
- tar xf hadoop-2.6.0.tar.gz
- export HADOOP_CLIENT_OPTS="-Xmx2G"
- export HADOOP_HOME=`pwd`/hadoop-2.6.0
- export LDBC_SNB_DATAGEN_HOME=`pwd`
- ./run.sh
- mkdir out
- cp -r substitution_parameters out/
notifications:
  slack: ldbcouncil:OrBanrJ7l0EHQbj8T5YdJYhd
  email: false
  on_success: change
  on_failure: always
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: out
  github-token: $GITHUB_TOKEN
  keep: true
  on:
    branch: master
