language: java
jdk:
  - openjdk8
python:
  - '2.7'
services:
  - docker
before_install:
  - cat /proc/cpuinfo
  - docker build . --tag ldbc/datagen
install: true
script:
  # test basic serializer
  - cp params-csv-basic.ini params.ini
  - docker run --rm --mount type=bind,source="$(pwd)/",target="/opt/ldbc_snb_datagen/out" --mount type=bind,source="$(pwd)/params.ini",target="/opt/ldbc_snb_datagen/params.ini" ldbc/datagen
notifications:
  slack: ldbcouncil:OrBanrJ7l0EHQbj8T5YdJYhd
  email: false
  on_success: change
  on_failure: always
