version: 2
jobs:
  build:
    resource_class: medium
    working_directory: ~/ldbc/ldbc_snb_datagen
    docker:
      - image: ldbc/datagen-build:0.0.1
    steps:
      - checkout
      - restore_cache:
          - m2-dep-{{ .Branch }}-
          - m2-dep-dev-
          - m2-dep-
      - mvn -ntp clean test-compile
      - save_cache:
          key: m2-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/.m2/repository
      - mvn -ntp test
      
